//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int AdminID { get; set; }
        [Required]
        [RegularExpression("[a-zA-Z]", ErrorMessage = "Please enter character Only.")]
        [Display(Name ="USERNAME")]
        public string Name { get; set; }
        public int Branch { get; set; }
        [Required]
        [RegularExpression("^(?=[^\\d].*?\\d)\\w(\\w|[!@#$%]){7,20}", ErrorMessage = "8 to 20 aplhanumeric characters and select special characters.")]
        [Display(Name ="PASSWORD")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    
        public virtual Branch Branch1 { get; set; }
    }
}
