//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int TransID { get; set; }
        public Nullable<int> PsID { get; set; }
        public string PAssengerName { get; set; }
        public Nullable<int> Age { get; set; }
        public string AcNumber { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public string Airport { get; set; }
        public string Destination { get; set; }
        public Nullable<decimal> Fare { get; set; }
    
        public virtual Passenger Passenger { get; set; }
    }
}
